### ISSUE TITLE
Edit alliance page throws exception

### ISSUE THREAD

**Issue by Yosodog** [Yosodog/game#44]
> Trying to get property of non-object (View: C:\Sites\game\resources\views\alliance\edit.blade.php)

Not descriptive exception, but something is trying to be accessed and it doesn't exist.

**Comment by Yosodog** [comment]
Seems this is thrown when someone not in the alliance tries to access the edit page. Probably a good idea to throw some validation before all the edit shit to make sure they're in the alliance and have permissions to edit the alliance. @LordStrum

**Comment by LordStrum** [comment]
Fixed, will be submitted in a later pull request.
