### ISSUE TITLE
Message Recepients

### ISSUE THREAD

**Issue by JFreer123** [Yosodog/game#73]
![image](https://user-images.githubusercontent.com/20909838/32253868-304bcd88-be95-11e7-9d54-13bf676ca4a4.png)

Yosodog doesn't appear 😭

**Comment by Yosodog** [comment]
Yeah this is something I'm aware of. I have no fucking idea why I didn't put it in there.

**Comment by Yosodog** [comment]
Found a DUPLICATE #45
